import Head from "next/head";
import SignupForm from "../components/SignupForm";

// import { LockOutlinedIcon } from "@mui/icons-material";

export default function Signup() {
  return (
    <>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignupForm />
    </>
  );
}
